version: '2.1'

orbs:
  terraform: circleci/terraform@3.1.0

executors:
  main:
    working_directory: ~/project/
    docker:
      - image: cimg/base:2022.09

jobs:
  test:
    executor: main
    steps:
      - checkout
      - terraform/install:
          terraform_version: 1.3.1
      - run:
          name: "Download and install terraform-docs"
          command: |
            set -euo pipefail
            cd ~
            mkdir -p ~/bin
            curl -sSLO https://github.com/terraform-docs/terraform-docs/releases/download/v${TERRAFORM_DOCS_VERSION}/terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz
            curl -sSLO https://github.com/terraform-docs/terraform-docs/releases/download/v${TERRAFORM_DOCS_VERSION}/terraform-docs-v${TERRAFORM_DOCS_VERSION}.sha256sum
            [ $(sha256sum terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz | cut -f1 -d' ') = $(grep linux-amd64 terraform-docs-v${TERRAFORM_DOCS_VERSION}.sha256sum | cut -f1 -d' ') ]
            tar -xf terraform-docs-v${TERRAFORM_DOCS_VERSION}-linux-amd64.tar.gz
            mv terraform-docs ~/bin/terraform-docs
          environment:
            TERRAFORM_DOCS_VERSION: "0.16.0"
      - run:
          name: "Download and install go"
          command: |
            set -euo pipefail
            cd ~
            mkdir -p ~/bin
            curl -sSLO https://go.dev/dl/go${GO_VERSION}.linux-amd64.tar.gz
            [ $(sha256sum go${GO_VERSION}.linux-amd64.tar.gz | cut -f1 -d' ') = "${GO_CHECKSUM}" ]
            tar -xzvf go${GO_VERSION}.linux-amd64.tar.gz
            sudo mv go /usr/local
            echo 'export PATH=$PATH:/usr/local/go/bin' >> $BASH_ENV
          environment:
            GO_VERSION: "1.20.4"
            GO_CHECKSUM: "698ef3243972a51ddb4028e4a1ac63dc6d60821bf18e59a807e051fee0a385bd"
      - run: echo 'export PATH=~/bin:$PATH' >> $BASH_ENV
      - run: make update_docs
      - run: make format_terraform
      - run: make imports
      - run: make tidy
      - run: make lint_go
      - run: git diff --exit-code

workflows:
  version: 2
  main:
    jobs:
      - test
